# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e70af8d55bf6dd4f6a1283b658cb9e4eb48280b37cee9a41f12fa8569a742719af39a597d0244b28b81e66813d63f064537f0c8be8380b223b1cb9f1a24c16aa

test:
  secret_key_base: b274cad03825ab9fd374de3ac603e58c36040abb672b8dec28d649684ff28e61515fae9e6d39af94f19d1689704cd0b379777d2d083b51f76edbb03a88a4ad21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
